package compass;

/** Internal domain vocabulary kept together because these types carry no logic. */
enum Capability { VERIFIED, UNKNOWN, BLOCKED }
enum CombatStyle { MELEE_STAB, MELEE_SLASH, MELEE_CRUSH, RANGED, MAGIC, HYBRID }
enum GearBudgetTier { F2P, BUDGET, MIDGAME, HIGH_END, BIS }
enum GoalNodeKind { SKILL, SKILL_LEVEL, TRAINING_METHOD, QUEST, MINIQUEST,
    ITEM, GEAR, ACTIVITY, PVM_ENCOUNTER, SLAYER, MINIGAME, ACCESS, DIARY,
    CLUE, STASH, TRANSPORTATION, SHOP, CURRENCY, SPELL, SPELLBOOK, PRAYER,
    RECURRING_OPPORTUNITY, PREPARATION_ACTION, COMBAT_ACHIEVEMENT, RESOURCE,
    META }
enum GoalRelation { AUTOMATIC, DIRECT, PREREQUISITE,
    FALLBACK, CHECK_NEEDED, BLOCKED }
enum GuidanceStepState { COMPLETE, ACTION, CHECK_NEEDED, WARNING, BLOCKED }
enum InfrastructureEvidenceKind { POH_ACCESS, POH_FURNITURE,
    STORAGE_CAPABILITY, TRANSPORT_ROUTE }
enum InfrastructureMilestoneState { COMPLETE, ACTIONABLE, CHECK_NEEDED,
    REQUIREMENTS_MISSING, NOT_APPLICABLE }
enum ItemQuantityMode { EXACT, AT_LEAST }
enum ItemRequirementScope { CARRIED, EQUIPPED, CARRIED_OR_EQUIPPED,
    IMMEDIATELY_USABLE, OWNED_OR_RETRIEVABLE }
enum BankingMode { NONE, OPTIONAL, CONVENTIONAL_BANK_LOOP,
    UIM_NOTED_ITEM_SERVICE, LOCAL_PROCESSING, UNKNOWN }
enum MethodCostTier { PROFITABLE, FREE, VERY_LOW, LOW, MODERATE, HIGH, VERY_HIGH }
enum ProgressMilestoneType { SKILL_LEVEL, PLAN_STEP, GOAL_DEPENDENCY, QUEST,
    INFRASTRUCTURE, TRANSPORT, SLAYER_UNLOCK, EQUIPMENT, DIARY }
enum ProgressionObjectiveType { OUTFIT, COLLECTION_LOG, GEAR, UNTRADEABLE, CURRENCY }
enum RequirementState { VERIFIED, CHECK_NEEDED, BLOCKED }
enum SlayerState { UNKNOWN, NO_TASK, CHOICE_PENDING, ASSIGNED }
enum SlayerRequiredItemUse { EQUIPPED, CARRIED_OR_EQUIPPED }
enum SlayerDecision { DO, SKIP, BLOCK, PREP_FIRST, ALTERNATIVE }
enum UimInventoryKind { USE_AS_IS, USE_LOW_FOOTPRINT_ALTERNATIVE,
    PRODUCTIVELY_CONSUME_RESOURCES, USE_VERIFIED_SAFE_STORAGE,
    BUILD_HIGH_VALUE_SAFE_STORAGE, USE_RESTRICTED_RETRIEVAL,
    USE_DANGEROUS_DEATH_STORAGE, UNRESOLVED }
