package com.udderlywet.osrsstrategist;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.inject.Singleton;

/** Stable task mechanics used to enrich live Slayer assignments. */
@Singleton
public class SlayerTaskProfileCatalog
{
    private final List<SlayerTaskProfile> profiles = join(Arrays.asList(
            p("dust-devils", a("dust devil", "dust devils"),
                    a("Slayer helmet", "Slayer helmet (i)", "Facemask"),
                    "Catacombs of Kourend unless the live assignment specifies another area.",
                    "Magic bursting/barraging is strong in multicombat when the build, rune supply and budget support it; otherwise use a build-legal conventional style.",
                    "A facemask or Slayer helmet must be worn. Never route to the Wilderness Slayer Cave unless Wilderness methods are explicitly enabled.",
                    CapabilityState.UNKNOWN, CapabilityState.VERIFIED, true,
                    Collections.emptyList(),
                    "Do not skip automatically: compare rune/prayer cost and the assigned location against the account's current goals."),
            p("aberrant-spectres", a("aberrant spectre", "aberrant spectres"),
                    a("Slayer helmet", "Slayer helmet (i)", "Nose peg"),
                    "Slayer Tower or another non-Wilderness location allowed by the assignment.",
                    "Use a build-legal style and protect against their Magic attacks when appropriate.",
                    "A nose peg or Slayer helmet is mandatory protection against their stat-draining fumes."),
            p("gargoyles", a("gargoyle", "gargoyles"),
                    a("Rock hammer", "Rock thrownhammer", "Granite hammer"),
                    "Slayer Tower. Use the basement only when the live task/access state supports it.",
                    "Melee is a practical default; crush and Magic are useful weaknesses, but owned gear should decide the actual style.",
                    "A rock hammer or equivalent is required to finish ordinary gargoyles. Gargoyle Smasher can automate the finishing blow when unlocked."),
            p("kurasks", a("kurask", "kurasks"),
                    a("Leaf-bladed spear", "Leaf-bladed sword", "Leaf-bladed battleaxe", "Broad bolts", "Broad arrows", "Slayer's staff"),
                    "Fremennik Slayer Dungeon unless the assignment specifies another legal location.",
                    "Use a leaf-bladed weapon, broad ammunition, or Magic Dart. Ordinary weapons cannot damage Kurasks.",
                    "This task has a hard weapon restriction, so at least one legal damage option must be verified before the setup is ready."),
            p("turoths", a("turoth", "turoths"),
                    a("Leaf-bladed spear", "Leaf-bladed sword", "Leaf-bladed battleaxe", "Broad bolts", "Broad arrows", "Slayer's staff"),
                    "Fremennik Slayer Dungeon unless the live assignment specifies another legal location.",
                    "Use a leaf-bladed weapon, broad ammunition, or Magic Dart.",
                    "Turoths share the leafy damage restriction with Kurasks, so ordinary weapons should never be suggested."),
            p("banshees", a("banshee", "banshees", "twisted banshee", "twisted banshees"),
                    a("Slayer helmet", "Slayer helmet (i)", "Earmuffs"),
                    "Use the safest reachable location allowed by the task.",
                    "Use any build-legal combat style after the hearing protection requirement is satisfied.",
                    "Earmuffs or a Slayer helmet protect against the Banshee scream mechanic."),
            p("cockatrices", a("cockatrice", "cockatrices"),
                    a("Mirror shield"),
                    "Fremennik Slayer Dungeon unless the task specifies another legal area.",
                    "Use a one-handed build-legal weapon with the mirror shield.",
                    "The mirror-shield mechanic constrains the off-hand slot, so two-handed weapon recommendations should not be used by default."),
            p("basilisks", a("basilisk", "basilisks"),
                    a("Mirror shield"),
                    "Fremennik Slayer Dungeon for ordinary basilisks unless the assignment points to another variant.",
                    "Use a one-handed build-legal weapon with the required gaze protection for ordinary basilisks.",
                    "Basilisk Knights have separate quest access and setup and should not be treated as identical to ordinary basilisks."),
            p("wall-beasts", a("wall beast", "wall beasts"),
                    a("Spiny helmet", "Slayer helmet", "Slayer helmet (i)"),
                    "Lumbridge Swamp Caves.",
                    "Use any build-legal style after head protection is equipped.",
                    "A spiny helmet or Slayer helmet protects from the wall-beast grab while moving through their attack points."),
            p("rockslugs", a("rockslug", "rockslugs", "rock slug", "rock slugs"),
                    a("Bag of salt", "Brine sabre"),
                    "Fremennik Slayer Dungeon unless the live task location overrides it.",
                    "Use a build-legal style and keep the finishing item available.",
                    "Rockslugs need salt or an appropriate alternative to finish them at low Hitpoints."),
            p("desert-lizards", a("desert lizard", "desert lizards"),
                    a("Ice cooler"),
                    "Use the Kharidian Desert task area allowed by the assignment.",
                    "Use a build-legal style and keep Ice coolers in the inventory.",
                    "Desert lizards require an Ice cooler to finish them at low Hitpoints."),
            p("nechryaels", a("nechryael", "nechryaels", "greater nechryael", "greater nechryaels"),
                    Collections.emptyList(),
                    "Catacombs of Kourend is a strong non-Wilderness option when reachable and allowed by the assignment.",
                    "Multitarget Magic can be efficient when the build and rune supply support it; otherwise use a legal conventional style.",
                    "Variants and summons make fixed supply or kill-time estimates unreliable.",
                    CapabilityState.UNKNOWN, CapabilityState.VERIFIED, false,
                    Collections.emptyList(),
                    "Keep or extend only when the live location, rune supply, and combat goals make multitarget Magic worthwhile."),
            p("bloodvelds", a("bloodveld", "bloodvelds", "mutated bloodveld", "mutated bloodvelds"),
                    Collections.emptyList(),
                    "Prefer a safe reachable non-Wilderness location that matches the live assignment.",
                    "Choose the style from owned gear and the exact assigned location.",
                    "Locations differ enough that cannon or multicombat availability needs live location evidence."),
            p("cave-horrors", a("cave horror", "cave horrors"),
                    a("Witchwood icon", "Slayer helmet", "Slayer helmet (i)"),
                    "Mos Le'Harmless Caves after Cabin Fever.",
                    "Use a build-legal style while the required head/neck protection is equipped.",
                    "A witchwood icon or Slayer helmet protects against the cave horror scream; Mos Le'Harmless access must also be verified.",
                    CapabilityState.UNKNOWN, CapabilityState.UNKNOWN, false,
                    a("Black mask"), "For Iron accounts, the black mask is a major Slayer progression objective."),
            p("mogres", a("mogre", "mogres"),
                    a("Fishing explosive", "Super fishing explosive"),
                    "Mudskipper Point after the Mogre miniquest setup is complete.",
                    "Use a build-legal combat style after luring a mogre with the explosive.",
                    "The fishing explosive is used on an ominous fishing spot to make a mogre appear."),
            p("killerwatts", a("killerwatt", "killerwatts"),
                    a("Insulated boots"),
                    "Killerwatt plane through the Draynor Manor portal.",
                    "Use a build-legal style with insulated boots equipped.",
                    "Insulated boots are mandatory protection from the plane's electrical damage."),
            p("fever-spiders", a("fever spider", "fever spiders"),
                    a("Slayer gloves"),
                    "Braindeath Island brewery basement after Rum Deal access is verified.",
                    "Use a build-legal style with Slayer gloves equipped.",
                    "Slayer gloves are mandatory; verify Rum Deal access before travelling."),
            p("brine-rats", a("brine rat", "brine rats"),
                    Collections.emptyList(),
                    "Brine Rat Cavern after Olaf's Quest.",
                    "Use a build-legal sustainable style; the exact weapon should come from owned gear.",
                    "The cavern is quest-gated, so Olaf's Quest completion must be observed before routing here.",
                    CapabilityState.UNKNOWN, CapabilityState.UNKNOWN, false,
                    a("Brine sabre"), "Iron accounts may value the brine sabre drop for underwater combat progression."),
            p("skeletal-wyverns", a("skeletal wyvern", "skeletal wyverns"),
                    a("Elemental shield", "Mind shield", "Dragonfire shield", "Ancient wyvern shield"),
                    "Asgarnian Ice Dungeon.",
                    "Use a one-handed build-legal weapon with a verified wyvern-breath shield.",
                    "Ordinary antifire protection does not replace a valid wyvern shield; the off-hand requirement rules out two-handed defaults."),
            p("smoke-devils", a("smoke devil", "smoke devils", "thermonuclear smoke devil"),
                    a("Slayer helmet", "Slayer helmet (i)", "Facemask"),
                    "Smoke Devil Dungeon for the ordinary task unless a live boss choice is explicit.",
                    "Multitarget Magic is effective for ordinary smoke devils when runes, spellbook, prayer and location are verified.",
                    "A facemask or Slayer helmet is mandatory. Do not silently turn the assignment into a boss task.",
                    CapabilityState.UNKNOWN, CapabilityState.VERIFIED, false,
                    Collections.emptyList(), "Compare barrage cost with the player's Slayer and Magic goals before extending."),
            p("wyrms", a("wyrm", "wyrms"), Collections.emptyList(),
                    "Mount Karuulm; verify heat protection before entering the dungeon.",
                    "Use a build-legal ranged or melee setup selected from owned gear.",
                    "Karuulm dungeon heat protection/access must be verified; do not assume generic boots satisfy it."),
            p("drakes", a("drake", "drakes"), Collections.emptyList(),
                    "Mount Karuulm; verify heat protection before entering the dungeon.",
                    "Use a sustainable build-legal setup and verify the chosen anti-dragonfire coverage.",
                    "Drake breath and Karuulm heat are separate preparation concerns; neither should be inferred from a generic combat loadout."),
            p("hydras", a("hydra", "hydras", "alchemical hydra"), Collections.emptyList(),
                    "Mount Karuulm. Ordinary hydras and the Alchemical Hydra are different encounters.",
                    "Use the assignment's ordinary-monster setup unless the live state explicitly selects the boss encounter.",
                    "Verify Karuulm heat protection and do not promote a generic hydra assignment to boss readiness."),
            p("vampyres", a("vampyre", "vampyres", "vampire", "vampires"),
                    a("Silver weapon", "Ivandis flail", "Blisterwood flail"),
                    "Use a reachable non-Wilderness Morytania location matching the assigned vampyre tier.",
                    "The legal weapon depends on the exact vampyre tier and quest progression.",
                    "Vampyre tiers have different immunity and weapon rules, so verify the live variant before choosing a weapon."),
            p("waterfiends", a("waterfiend", "waterfiends"), Collections.emptyList(),
                    "Ancient Cavern only after its access route is verified; use another assigned legal location when applicable.",
                    "Crush is generally appropriate, but the actual weapon must be build-legal and owned.",
                    "Ancient Cavern access and aggressive surrounding monsters make this an access/setup check, not a generic low-risk location."),
            p("kalphites", a("kalphite", "kalphites"), Collections.emptyList(),
                    "Use the safest task-valid non-Wilderness lair supported by live access evidence.",
                    "Choose a sustainable build-legal style for the exact kalphite variant.",
                    "Cannon and multicombat suitability depend on the selected room; Kalphite Queen is a separate PvM encounter."),
            p("dagannoths", a("dagannoth", "dagannoths"), Collections.emptyList(),
                    "Choose a task-valid non-Wilderness location whose access is already proven.",
                    "Use a sustainable legal style; multitarget options depend on the exact room.",
                    "Lighthouse, Catacombs and Waterbirth variants have different access and combat context; Dagannoth Kings are separate PvM encounters."),
            p("black-demons", a("black demon", "black demons"),
                    Collections.emptyList(),
                    "Use a reachable task-valid non-Wilderness location unless risk is explicitly enabled.",
                    "Use a safespot or sustainable build-legal setup appropriate to the exact variant.",
                    "Demonic gorillas and Wilderness variants require their own quest, mechanics and risk evidence."),
            p("greater-demons", a("greater demon", "greater demons"), Collections.emptyList(),
                    "Use a reachable non-Wilderness task area unless Wilderness risk is explicitly enabled.",
                    "Use a sustainable build-legal style selected from owned gear.",
                    "Tormented demons, Kril Tsutsaroth and Wilderness variants are separate encounters and must not inherit ordinary-task readiness.",
                    CapabilityState.UNKNOWN, CapabilityState.UNKNOWN, true,
                    Collections.emptyList(), "Keep or skip according to the assigned location and current combat goals."),
            p("crawling-hands", a("crawling hand", "crawling hands"), Collections.emptyList(),
                    "Slayer Tower after Morytania access is verified.",
                    "Use any build-legal conventional style.",
                    "The Slayer Tower route requires Priest in Peril access; do not route an F2P or unverified account there."),
            p("cave-crawlers", a("cave crawler", "cave crawlers"), Collections.emptyList(),
                    "Fremennik Slayer Dungeon when that access route is available.",
                    "Use a sustainable build-legal style and carry poison protection.",
                    "Cave crawlers poison; verify an antipoison source before treating the setup as ready."),
            p("cave-slimes", a("cave slime", "cave slimes"), Collections.emptyList(),
                    "Lumbridge Swamp Caves with a verified safe light source.",
                    "Use a sustainable build-legal style and carry poison protection.",
                    "The cave route needs a safe light source and cave slimes can poison."),
            p("pyrefiends", a("pyrefiend", "pyrefiends"), Collections.emptyList(),
                    "Fremennik Slayer Dungeon unless the task specifies another reachable area.",
                    "Use a build-legal style chosen from owned gear.",
                    "Do not infer a Wilderness route or cannon placement without live location evidence."),
            p("infernal-mages", a("infernal mage", "infernal mages"), Collections.emptyList(),
                    "Slayer Tower after Morytania access is verified.",
                    "Use a build-legal setup with appropriate Magic defence or protection.",
                    "Slayer Tower access and the monster's Magic attacks should be included in preparation."),
            p("jellies", a("jelly", "jellies", "warped jelly", "warped jellies"), Collections.emptyList(),
                    "Use a reachable non-Wilderness location matching the assigned variant.",
                    "Use a build-legal style; multitarget Magic is location-dependent.",
                    "Ordinary and warped variants occupy different areas, so burst or barrage suitability needs live location evidence."),
            p("harpie-bug-swarms", a("harpie bug swarm", "harpie bug swarms"),
                    a("Lit bug lantern"),
                    "North-east of Tai Bwo Wannai after Karamja access is verified.",
                    "Use a build-legal one-handed or two-handed style after the lit lantern is carried.",
                    "A lit bug lantern is required to damage harpie bug swarms."),
            p("zygomites", a("zygomite", "zygomites", "mutated zygomite", "mutated zygomites"),
                    a("Fungicide spray"),
                    "Use the task-valid zygomite area supported by live access evidence.",
                    "Use a build-legal style and keep fungicide charges available.",
                    "Fungicide spray is required to finish zygomites; verify remaining charges rather than assuming a bottle is usable."),
            p("abyssal-demons", a("abyssal demon", "abyssal demons"), Collections.emptyList(),
                    "Slayer Tower or Catacombs of Kourend when the chosen route is already accessible.",
                    "Use a build-legal melee setup or verified multitarget Magic setup for the exact room.",
                    "Teleporting attacks and room layout affect positioning; Abyssal Sire is a separate boss encounter.",
                    CapabilityState.UNKNOWN, CapabilityState.UNKNOWN, false,
                    a("Abyssal whip"), "Iron accounts may value the abyssal whip drop; extension depends on the selected location and goal."),
            p("dark-beasts", a("dark beast", "dark beasts"), Collections.emptyList(),
                    "Mourner Tunnels only after the required elf quest access is observed.",
                    "Use a sustainable build-legal combat style from owned gear.",
                    "Do not route here until Mourner Tunnels access is proven.",
                    CapabilityState.UNKNOWN, CapabilityState.UNKNOWN, false,
                    a("Dark bow"), "Usually decide from current unlock goals and whether the dark bow drop matters to the account."),
            p("cave-kraken", a("cave kraken", "cave krakens"), Collections.emptyList(),
                    "Kraken Cove while assigned cave kraken.",
                    "Use Magic and disturb the whirlpool with a ranged or Magic attack.",
                    "The Kraken boss is a separate encounter; ordinary cave kraken still require an active assignment."),
            p("warped-creatures", a("warped terrorbird", "warped terrorbirds", "warped tortoise", "warped tortoises"),
                    a("Crystal chime"),
                    "Poison Waste Slayer Dungeon after The Path of Glouphrie.",
                    "Use a build-legal style after weakening the creature with the crystal chime.",
                    "The Path of Glouphrie access and crystal chime are mandatory; ordinary weapons alone do not bypass the defence mechanic."),
            p("sulphur-lizards", a("sulphur lizard", "sulphur lizards"),
                    a("Boots of stone", "Boots of brimstone", "Granite boots"),
                    "Mount Karuulm after the dungeon heat-protection route is verified.",
                    "Use a sustainable build-legal style.",
                    "A valid Karuulm heat-protection item must be equipped before entering the dangerous floor."),
            p("spiritual-creatures", a("spiritual ranger", "spiritual rangers",
                    "spiritual mage", "spiritual mages", "spiritual warrior", "spiritual warriors"),
                    Collections.emptyList(),
                    "God Wars Dungeon only after the live route and faction protection are verified.",
                    "Match the build-legal style to the assigned spiritual creature and owned gear.",
                    "God protection, dungeon access and the exact spiritual variant must be checked before travel."),
            p("elves", a("elf", "elves"), Collections.emptyList(),
                    "Use a reachable task-valid Tirannwn or Prifddinas location supported by quest state.",
                    "Use a sustainable build-legal style selected from owned gear.",
                    "Elf locations have materially different quest and transport requirements; do not assume Prifddinas access."),
            p("ankous", a("ankou", "ankous"), Collections.emptyList(),
                    "Use the safest reachable non-Wilderness task location, such as the Stronghold of Security when suitable.",
                    "Use a safespot or sustainable build-legal setup appropriate to the chosen room.",
                    "Wilderness and Catacombs variants need separate risk and access evidence."),
            p("suqahs", a("suqah", "suqahs"), Collections.emptyList(),
                    "Lunar Isle only after Lunar Diplomacy access and transport are observed.",
                    "Use a sustainable build-legal style with food or protection appropriate to their mixed attacks.",
                    "Do not route to Lunar Isle until the quest access and return transport are proven."),
            p("trolls", a("troll", "trolls"), Collections.emptyList(),
                    "Choose a non-Wilderness troll location whose mountain or island access is already proven.",
                    "Use a sustainable build-legal style for the exact troll variant.",
                    "Troll variants, multicombat areas and access routes differ; cannon suitability needs live location evidence."),
            p("blue-dragons", a("blue dragon", "blue dragons"),
                    a("Anti-dragon shield", "Dragonfire shield", "Dragonfire ward"),
                    "Use a reachable non-Wilderness blue-dragon location with a verified escape route.",
                    "Use a build-legal ranged, Magic or one-handed melee setup with dragonfire protection.",
                    "Verify the selected protection and location; ordinary antifire assumptions do not replace live equipment evidence."),
            p("black-dragons", a("black dragon", "black dragons"),
                    a("Anti-dragon shield", "Dragonfire shield", "Dragonfire ward"),
                    "Use a reachable non-Wilderness task location unless Wilderness risk is explicitly enabled.",
                    "Use a build-legal style with compatible dragonfire protection.",
                    "King Black Dragon and Wilderness variants are separate PvM/risk contexts."),
            p("steel-dragons", a("steel dragon", "steel dragons"),
                    a("Anti-dragon shield", "Dragonfire shield", "Dragonfire ward"),
                    "Use a reachable task-valid metal-dragon location after access is verified.",
                    "Use a build-legal setup with verified dragonfire protection and appropriate damage type.",
                    "Metal dragons combine dragonfire and strong conventional attacks; food and potion quantities remain setup-dependent."),
            p("mithril-dragons", a("mithril dragon", "mithril dragons"),
                    a("Anti-dragon shield", "Dragonfire shield", "Dragonfire ward"),
                    "Ancient Cavern only after Barbarian Training access is observed.",
                    "Use a build-legal setup with verified dragonfire protection and a safe escape plan.",
                    "Ancient Cavern access and the dragon's multiple attack styles make this a higher-risk preparation task."),
            p("fossil-island-wyverns", a("fossil island wyverns",
                    "spitting wyvern", "spitting wyverns",
                    "taloned wyvern", "taloned wyverns", "long-tailed wyvern", "long-tailed wyverns",
                    "ancient wyvern", "ancient wyverns"),
                    a("Elemental shield", "Mind shield", "Dragonfire shield", "Ancient wyvern shield"),
                    "Wyvern Cave after Fossil Island access is verified.",
                    "Use a one-handed build-legal weapon with valid wyvern-breath protection.",
                    "Fossil Island access and the exact wyvern variant must be known; ordinary antifire does not replace a valid shield.")),
            additionalProfiles());

    /** Common RuneLite task identities that previously fell through generically. */
    private static List<SlayerTaskProfile> additionalProfiles()
    {
        return Arrays.asList(
                ordinary("aviansies", "Aviansies", "God Wars Dungeon after route and faction protection are verified.", "Use Ranged and verify the assigned aviansie variant."),
                ordinary("bandits", "Bandits", "Use the task-valid desert or Wilderness location selected by the assignment.", "Choose a legal style; Wilderness variants require explicit risk acceptance."),
                ordinary("bats", "Bats", "Use a reachable low-risk bat location matching the assignment.", "Use any build-legal conventional style."),
                ordinary("bears", "Bears", "Use a reachable non-Wilderness bear location.", "Callisto and Artio are separate Wilderness boss decisions."),
                ordinary("black-knights", "Black Knights", "Use a reachable Black Knight location supported by access evidence.", "Use any sustainable build-legal style."),
                ordinary("cave-bugs", "Cave bugs", "Lumbridge Swamp Caves with a verified safe light source.", "Bring cave access equipment and use a build-legal style."),
                ordinary("chaos-druids", "Chaos druids", "Use a reachable non-Wilderness location unless risk is enabled.", "Their herb drops can matter to Iron accounts; compare travel with the task size."),
                ordinary("cows", "Cows", "Use a nearby reachable cow field.", "Use any legal style; hides can support early Crafting."),
                ordinary("crabs", "Crabs", "Use the exact reachable crab variant named by the assignment.", "Low-attention combat may fit AFK sessions, but verify variant access."),
                ordinary("crocodiles", "Crocodiles", "Use the assigned Kharidian Desert area with water/heat preparation.", "Use a sustainable legal style and verify desert supplies."),
                ordinary("dark-warriors", "Dark warriors", "Use the assignment's verified location; do not assume a Wilderness route.", "Use any sustainable build-legal style."),
                ordinary("dogs", "Dogs", "Use a reachable non-Wilderness dog variant matching the assignment.", "Temple Guardian and dangerous variants require separate access checks."),
                ordinary("dwarves", "Dwarves", "Use a reachable dwarf or Black Guard location matching the assignment.", "Use any build-legal conventional style."),
                ordinary("earth-warriors", "Earth warriors", "Use the assignment location only after its risk/access is verified.", "Do not route a Hardcore account into the Wilderness by default."),
                ordinary("ents", "Ents", "Use a verified task-valid location; Wilderness ents require explicit risk acceptance.", "Choose a legal style and preserve useful log drops when relevant."),
                ordinary("fire-giants", "Fire giants", "Use a reachable non-Wilderness dungeon matching current quest access.", "Use a safespot or sustainable legal setup; Branda is a separate boss encounter."),
                ordinary("flesh-crawlers", "Fleshcrawlers", "Stronghold of Security when reachable and suitable.", "Use a sustainable build-legal style and value herb drops on early Irons."),
                ordinary("ghosts", "Ghosts", "Use a reachable non-Wilderness ghost location matching the task.", "Revenants and boss variants are separate risk contexts."),
                ordinary("ghouls", "Ghouls", "Morytania only after Priest in Peril access is observed.", "Use any sustainable build-legal style."),
                ordinary("goblins", "Goblins", "Use a nearby low-risk goblin location.", "God Wars sergeants are separate encounter contexts."),
                dragon("green-dragons", "Green dragons", "Use a safe non-Wilderness route when available; Wilderness routes require explicit risk acceptance."),
                ordinary("hellhounds", "Hellhounds", "Use a reachable non-Wilderness location matching the assignment.", "Cerberus requires its own Slayer/boss readiness decision."),
                ordinary("hill-giants", "Hill giants", "Use a reachable low-risk location; giant keys may support an explicit Obor goal.", "Use a sustainable legal style; Obor is a separate keyed encounter."),
                ordinary("hobgoblins", "Hobgoblins", "Use a reachable non-Wilderness location.", "Use any sustainable build-legal style."),
                ordinary("icefiends", "Icefiends", "Use a reachable icy-area spawn matching the assignment.", "Use any legal style after verifying cold-area access."),
                ordinary("ice-giants", "Ice giants", "Use a reachable non-Wilderness ice dungeon.", "Eldric is a separate boss encounter."),
                ordinary("ice-warriors", "Ice warriors", "Use a reachable non-Wilderness ice dungeon.", "Use any sustainable build-legal style."),
                ordinary("jungle-horrors", "Jungle horrors", "Mos Le'Harmless only after Cabin Fever access is observed.", "Use a legal style and verify island transport."),
                ordinary("lava-dragons", "Lava Dragons", "Wilderness Lava Dragon Isle only with explicit risk acceptance.", "Use disposable risk-aware gear, dragonfire protection, and an escape route."),
                ordinary("lesser-demons", "Lesser demons", "Use a reachable non-Wilderness location unless risk is enabled.", "Use a safespot or sustainable build-legal setup."),
                ordinary("lizardmen", "Lizardmen", "Use the exact reachable Shayzien/Kourend variant supported by access evidence.", "Shamans require separate protection and encounter preparation."),
                ordinary("magic-axes", "Magic axes", "Use only the assignment location after Wilderness/access status is known.", "Prefer a safe alternative for Hardcore accounts."),
                ordinary("minotaurs", "Minotaurs", "Stronghold of Security when reachable.", "Use any low-risk build-legal style."),
                ordinary("monkeys", "Monkeys", "Use the exact reachable monkey variant supported by quest access.", "Demonic gorillas are a separate mechanics-heavy encounter."),
                ordinary("moss-giants", "Moss giants", "Use a reachable non-Wilderness location; mossy keys can support a Bryophyta goal.", "Use a sustainable style; Bryophyta is a separate keyed encounter."),
                ordinary("otherworldly-beings", "Otherworldly beings", "Zanaris only after fairy-ring access is proven.", "Use any sustainable build-legal style."),
                ordinary("pirates", "Pirates", "Use a reachable non-Wilderness pirate location matching the assignment.", "Use any sustainable legal style."),
                dragon("red-dragons", "Red dragons", "Use a verified non-Wilderness red-dragon route and compatible protection."),
                ordinary("revenants", "Revenants", "Revenant Caves only with explicit Wilderness risk acceptance.", "Use disposable gear, verify bracelet/ether decisions, and keep a tested escape."),
                ordinary("rogues", "Rogues", "Use the assignment's verified location; Wilderness variants require risk acceptance.", "Use any sustainable build-legal style."),
                ordinary("scabarites", "Scabarites", "Use only after the relevant desert quest/access route is observed.", "Verify the exact scarab variant and desert supplies before travel."),
                ordinary("scorpions", "Scorpions", "Use a reachable non-Wilderness scorpion location.", "Scorpia and Wilderness variants are separate risk contexts."),
                ordinary("sea-snakes", "Sea snakes", "Use the verified island/quest route for the assigned variant.", "Verify transport before choosing a combat setup."),
                ordinary("shades", "Shades", "Use the exact reachable shade tier and Morytania access.", "Shade-burning supplies are a separate minigame/resource decision."),
                ordinary("shadow-warriors", "Shadow warriors", "Legends' Guild basement only after access is proven.", "Use any sustainable build-legal style."),
                ordinary("skeletons", "Skeletons", "Use a reachable non-Wilderness skeleton location.", "Vet'ion, Calvar'ion and Wilderness variants are separate risk contexts."),
                ordinary("sourhogs", "Sourhogs", "Use the verified Sourhog Cave route after A Porcine of Interest.", "Carry reinforced goggles or another verified protection option."),
                ordinary("terror-dogs", "Terror dogs", "Tarn's Lair only after Haunted Mine/lair access is proven.", "Verify the dungeon route and supplies before travel."),
                ordinary("tzhaar", "Tzhaar", "Use the reachable Mor Ul Rek/TzHaar area supported by account access.", "Jad and Zuk are separate challenge encounters."),
                ordinary("werewolves", "Werewolves", "Use a reachable Morytania werewolf location after access is proven.", "Verify the exact variant; Wolfbane mechanics are quest-context dependent."),
                ordinary("wolves", "Wolves", "Use a reachable non-Wilderness wolf location.", "Use any sustainable build-legal style."),
                ordinary("zombies", "Zombies", "Use a reachable non-Wilderness zombie location.", "Vorkath and Zogre variants are separate access/mechanics contexts."),
                ordinary("aquanites", "Aquanites", "Use only the live assignment's verified Sailing route and aquanite area.", "Verify the current variant, protection and return route before leaving port."),
                ordinary("araxytes", "Araxytes", "Araxyte Lair only after the live Slayer and access requirements are satisfied.", "Choose a task setup independently from Araxxor boss readiness."),
                ordinary("catablepon", "Catablepon", "Stronghold of Security after the exact room route is verified.", "Use a sustainable build-legal style and account for their stat-draining attack."),
                ordinary("custodian-stalkers", "Custodian Stalkers", "Use the live assignment's verified Custodia access route.", "Do not infer new-content mechanics or protection from the task name alone."),
                dragon("frost-dragons", "Frost dragons", "Grimstone only after the required Sailing access is observed; verify icy-breath protection separately."),
                ordinary("gryphons", "Gryphons", "The Great Conch after Troubled Tortugans and live gryphon-task access are observed.", "Shellbane Gryphon is a separate task-gated PvM preparation decision."),
                ordinary("lesser-nagua", "Lesser Nagua", "Use a reachable Neypotzli location supported by quest state.", "Verify the exact room and sustainable setup before travel."),
                ordinary("mammoths", "Mammoths", "Use only a task-valid location after Wilderness status is explicit.", "Hardcore accounts need a safer alternative; use disposable gear when Wilderness risk is accepted."),
                ordinary("metal-dragons", "Metal dragons", "Resolve the live task to a reachable bronze, iron, steel, mithril or other named metal-dragon location.", "Verify dragonfire protection and the exact tier instead of using a universal setup."),
                p("molanisks", a("Molanisks"), a("Slayer bell"),
                        "Dorgesh-Kaan South Dungeon after access is verified.",
                        "Use a Slayer bell to make the molanisk attackable, then use a build-legal style.",
                        "The bell and dungeon access must both be observed."),
                ordinary("spiritual-creature-task", "Spiritual creatures", "God Wars Dungeon after route and faction protection are verified.", "Resolve the exact ranger, mage, or warrior variant before choosing gear."),
                ordinary("warped-creature-task", "Warped Creatures", "Poison Waste Slayer Dungeon after The Path of Glouphrie.", "Carry the crystal chime and resolve the live terrorbird or tortoise variant."),
                bossTask("abyssal-sire-task", "The Abyssal Sire", false),
                bossTask("araxxor-task", "Araxxor", false),
                bossTask("barrows-task", "Barrows Brothers", false),
                bossTask("callisto-task", "Callisto", true),
                bossTask("cerberus-task", "Cerberus", false),
                bossTask("chaos-elemental-task", "The Chaos Elemental", true),
                bossTask("chaos-fanatic-task", "The Chaos Fanatic", true),
                bossTask("crazy-archaeologist-task", "Crazy Archaeologists", true),
                bossTask("deranged-archaeologist-task", "Deranged Archaeologist", false),
                bossTask("duke-sucellus-task", "Duke Sucellus", false),
                bossTask("graardor-task", "General Graardor", false),
                bossTask("giant-mole-task", "The Giant Mole", false),
                bossTask("grotesque-guardians-task", "The Grotesque Guardians", false),
                bossTask("jad-task", "TzTok-Jad", false),
                bossTask("kreearra-task", "Kree'arra", false),
                bossTask("kril-task", "K'ril Tsutsaroth", false),
                bossTask("maggot-king-task", "The Maggot King", false),
                bossTask("phantom-muspah-task", "The Phantom Muspah", false),
                bossTask("sarachnis-task", "Sarachnis", false),
                bossTask("scorpia-task", "Scorpia", true),
                bossTask("shellbane-gryphon-task", "The Shellbane Gryphon", false),
                bossTask("leviathan-task", "The Leviathan", false),
                bossTask("whisperer-task", "The Whisperer", false),
                bossTask("vardorvis-task", "Vardorvis", false),
                bossTask("venenatis-task", "Venenatis", true),
                bossTask("vetion-task", "Vet'ion", true),
                bossTask("vorkath-task", "Vorkath", false),
                bossTask("zilyana-task", "Commander Zilyana", false),
                bossTask("zuk-task", "TzKal-Zuk", false),
                bossTask("zulrah-task", "Zulrah", false));
    }

    private static SlayerTaskProfile ordinary(String id, String alias,
            String location, String note)
    {
        return p(id, a(alias), Collections.emptyList(), location,
                "Choose a sustainable build-legal style from observed gear.", note);
    }

    private static SlayerTaskProfile dragon(String id, String alias,
            String location)
    {
        return p(id, a(alias), a("Anti-dragon shield", "Dragonfire shield", "Dragonfire ward"),
                location, "Use a compatible one-handed or otherwise verified dragonfire-safe setup.",
                "Dragonfire protection and the exact location must be verified separately.");
    }

    private static SlayerTaskProfile bossTask(String id, String alias,
            boolean wilderness)
    {
        String risk = wilderness
                ? "This is a Wilderness boss task: require explicit risk acceptance, disposable gear and a tested escape."
                : "Use the encounter-specific PvM readiness profile; a live Slayer assignment does not prove gear, supplies or player execution.";
        return p(id, a(alias), Collections.emptyList(),
                "Open the matching encounter preparation before travelling.",
                "Use only an encounter-verified setup, not generic Slayer gear.",
                risk, CapabilityState.UNKNOWN, CapabilityState.UNKNOWN,
                wilderness, Collections.emptyList(),
                "Prioritize the boss variant only when its drops, CA, collection goal or Slayer value justify the setup.");
    }

    private static List<SlayerTaskProfile> join(List<SlayerTaskProfile> first,
            List<SlayerTaskProfile> second)
    {
        java.util.ArrayList<SlayerTaskProfile> result = new java.util.ArrayList<>(first);
        result.addAll(second);
        return Collections.unmodifiableList(result);
    }

    public SlayerTaskProfile profileFor(String taskName)
    {
        String task = n(taskName);
        if (task.isEmpty()) return null;
        for (SlayerTaskProfile profile : profiles)
            for (String alias : profile.getAliases())
            {
                String candidate = n(alias);
                if (task.equals(candidate) || task.contains(candidate)
                        || candidate.contains(task)) return profile;
            }
        return null;
    }

    public List<SlayerTaskProfile> all() { return profiles; }

    private static SlayerTaskProfile p(String id, List<String> aliases,
            List<String> required, String location, String style, String note)
    {
        return new SlayerTaskProfile(id, aliases, required, location, style, note);
    }

    private static SlayerTaskProfile p(String id, List<String> aliases,
            List<String> required, String location, String style, String note,
            CapabilityState cannon, CapabilityState multiTargetMagic,
            boolean wildernessVariant, List<String> ironObjectives,
            String decisionGuidance)
    {
        return new SlayerTaskProfile(id, aliases, required, location, style, note,
                cannon, multiTargetMagic, wildernessVariant, ironObjectives,
                decisionGuidance);
    }

    private static List<String> a(String... values) { return Arrays.asList(values); }
    private static String n(String value)
    {
        return value == null ? "" : value.trim().toLowerCase(Locale.ROOT);
    }
}
